# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0003_adapt_max_tag_length'),
        ('tagging', '0003_auto_20161115_0906'),
    ]

    operations = [
    ]
